### ISSUE TITLE
.gguf files not supported?

### ISSUE THREAD

**Issue by deltacloud9** [protectai/modelscan#111]
I tried to scan a .gguf file and receive the following:
![Screenshot 2024-03-01 at 10 13 04 AM](https://github.com/protectai/modelscan/assets/79772713/c9314d92-e414-4d9b-90ed-6e36c2fb8d4f)

I checked inside the modelscan-settings.toml and it appears that .gguf is not listed.

Are these file types not supported yet?

**Comment by chrisking** [comment]
Correct, they are not supported yet but we are doing research to understand the threats within them. We are not aware of the exact same issue that plague other formats like Pickle yet.

Once we identify anything that's a problem the work will make its way to ModelScan!

**Comment by seanpmorgan** [comment]
Closing as this isn't a bug. For the record, there does exist vulnerabilities in loading gguf and ggml files: 
https://www.databricks.com/blog/ggml-gguf-file-format-vulnerabilities
