### ISSUE TITLE
Improved output format for CI/CD pipeline

### ISSUE THREAD

**Issue by ryan-burt** [protectai/modelscan#38]
The console logging works well for inspection, but it is hard to link up to a downstream rule, such as fail pipeline on HIGH or CRITICAL issue severity. 

Two things would be great to have.
1. Reports return an exit code (non-zero depending on the issue severity). This could be propagated in cli.py instead of the hard coded 0
2. A JsonReport class which prints a json with something like issues --> severity --> list of issue instances for severity, errors --> list of errors

**Comment by iamfaisalkhan** [comment]
@ryan-burt Thanks for creating the issues. We already have the JSON reporting on our roadmap.  Created an issue specifically for the JSON reporting (See #40). This should get added pretty soon. 

The hard coded exit code 0 needs to be replaced with an appropriate exit code based on the results of the scanning. After some internal discussion and looking at some of the popular vulnerability scanning tools, we are going with the exit codes documented in issues #41. Please feel free to comment here or on those issues if you have additional feedback or suggestions.

**Comment by seanpmorgan** [comment]
Hi @ryan-burt thanks for the issue! I'm closing this as this is covered in #57. We expect to land this very soon
