### ISSUE TITLE
Add json as a reporting format

### ISSUE THREAD

**Issue by iamfaisalkhan** [protectai/modelscan#40]
Add JSON reporting to modelscan. 

**Acceptance Criteria**

- [ ] A cli flag `--json` that prints on console the modelscan report as JSON data structure
- [ ] A cli option `--json-file-output=<output_file_path>` that save the modelscan report as JSON data structure directly to the specified file
- [ ] JSON structure should list issues by severity

**Comment by swashko** [comment]
Tabled until JSON output format is decided

**Comment by seanpmorgan** [comment]
Superseded by #57. This should land soon
