### ISSUE TITLE
Exception: name 'tensorflow' is not defined

### ISSUE THREAD

**Issue by robsanity** [protectai/modelscan#65]
Trying to run modelscan on WSL with Ubuntu 22.04 but after multiple tries of installation, when running the command
modelscan -p /mymodelpath

i keep having this error
Exception: name 'tensorflow' is not defined
even if everything looks correctly installed
Any Hints?

**Comment by seanpmorgan** [comment]
Closing, as this appears to be a missing dependency that can be installed as mentioned above. Please re-open this issue if there is more.
